apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/ogawa-yasuyuki-0012166/argocd-sample
    newTag: 7ff106c03293c64698a538a5241d69fe356d48a8