apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/ogawa-yasuyuki-0012166/argocd-sample
    newTag: 921d8fb9f8db98311719071dffeed232e5d5dc3d