apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/ogawa-yasuyuki-0012166/argocd-sample
    newTag: 8acec567a282027cd81d581065a1c3d3bc60cad8